# Ruff supports a top-level `src` option in lieu of isort's `src_paths` setting.
# All paths are relative to the project root, which is the directory containing the pyproject.toml.
builtins = ["_"]
fix = true
src = ["src", "tests"]
extend-include = ["*.ipynb"]
target-version = "py312"

[lint]
select = ["ALL"]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"/**/tests/**/*.py" = ["S101", "ARG", "FBT", "PLR2004", "S311"]

[format]
docstring-code-format = true
